name: CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

      version:
        description: 'Version to deploy/rollback to'
        required: false
        default: ''

      workflow:
        description: 'workflow to esecute'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"

      - name: Sleep for 1 minute
        run: |
          echo "Sleeping for 60 seconds..."
          sleep 60
          echo "Done."
